[package]
name = "context-file-concat"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.29"
eframe = { version = "0.29", default-features = true, features = ["default_fonts", "glow", "persistence"] }
tokio = { version = "1.0", features = ["full"] }
walkdir = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
camino = "1.1"
directories = "5.0"
regex = "1.0"
tree_magic_mini = "3.0"
chrono = { version = "0.4", features = ["serde"] }
rfd = "0.15"
dirs = "5.0"

# Für bessere Performance im Release-Build
[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"